export const cards = [
    {
        id: 1,
        name: 'Google Fonts',
        site: 'https://fonts.google.com/',
        logo: 'https://logos-world.net/wp-content/uploads/2021/03/Google-Fonts-Logo.png',
        category: 'Typography',
        description: 'A computer font and web services owned by Google',
    },
    {
        id: 2,
        name: 'Fonts in Use',
        site: 'https://fontsinuse.com/',
        logo: 'https://seeklogo.com/images/F/fonts-in-use-logo-6EA99A0816-seeklogo.com.png',
        category: 'Typography',
        description: 'An independent archive of typography',
    },
    {
        id: 3,
        name: 'Font Fabric',
        site: 'https://www.fontfabric.com/free-fonts/',
        logo: 'https://cdn.dribbble.com/users/58593/screenshots/1021155/media/79853350d5b66f10cfbeeea57094cf08.png?resize=400x300&vertical=center',
        category: 'Typography',
        description: 'Company for Font Type Design',
    },
    {
        id: 4, 
        name: 'Typo/Graphic',
        site: 'https://www.typographicposters.com/',
        logo: 'https://www.typographicposters.com/apple-touch-icon.png',
        category: 'Typography',
        description: 'Connect to Different Cultures Through Poster Design',
    },
    {
        id: 5,
        name: 'Color Hunt',
        site: 'https://colorhunt.co/',
        logo: 'https://colorhunt.co/img/color-hunt-logo-animation.gif',
        category: 'Color',
        description: 'Free and Open Platform For Color Inspiration',
    },
    {
        id: 6,
        name: 'Khroma',
        site: 'https://www.khroma.co/',
        logo: 'https://www.designupai.com/wp-content/uploads/2023/10/Khroma-Logo.png',
        category: 'Color',
        description: 'Uses AI to Learn which Colors You Like and Creates Palettes'
    },
    {
        id: 7, 
        name: 'Happy Hues',
        site: 'https://www.happyhues.co/',
        logo: 'https://uploads-ssl.webflow.com/6198a2e43048192ebafec2cc/63d13e7ca156bd4cf5d177b9_fDgNkoqEyjF1OI0HdDtD-S2EzhUKihaUVPAyJPjpL9k.png',
        category: 'Color',
        description: 'Curated Colors in Context',
    },
    {
        id: 8,
        name: 'Coolors',
        site: 'https://coolors.co/',
        logo: 'https://wpexpert.ca/wp-content/uploads/coolors-logo.jpg',
        category: 'Color',
        description: 'Fast Color Schemes Generator',    
    },
    {
        id: 9,
        name: 'Brand Colors',
        site: 'https://brandcolors.net/',
        logo: 'https://asset.brandfetch.io/id22o1wBNN/idlDger2sy.jpeg?updated=1706980420399',
        category: 'Color',
        description: 'Biggest Collection of Official Brand Color Codes'
    },
    {
        id: 10,
        name: 'DevDocs',
        site: 'https://devdocs.io/',
        logo: 'https://assets-global.website-files.com/61fc4082d1990015ce74e415/620fc3c7cba4a56fa0913796_Devdocs%20Logo%20Transpararent%20Dark.svg',
        category: 'Documentations',
        description: 'Combines multiple API documentations',
    },
    {
        id: 11,
        name: 'Figma',
        site: 'https://www.figma.com/',
        logo: 'https://cdn.sanity.io/images/599r6htc/localized/46a76c802176eb17b04e12108de7e7e0f3736dc6-1024x1024.png?w=804&h=804&q=75&fit=max&auto=format',
        category: 'Prototype',
        description: 'A collaborative web application for interface design',
    },
    {
        id: 12,
        name: 'Adobe XD',
        site: 'https://adobexdplatform.com/',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Adobe_XD_CC_icon.svg/1200px-Adobe_XD_CC_icon.svg.png',
        category: 'Prototype',
        description: 'A vector design tool for web and mobile applications',
    },
    {
        id: 13,
        name: 'Draw.io',
        site: 'https://app.diagrams.net/',
        logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC4nAmib81PtEdmLhV8wGMFq2YyFnG5jGRaw&usqp=CAU',
        category: 'Diagram',
        description: 'A free online diagram software'
    },
    {
        id: 14, 
        name: 'CSS Buttons',
        site: 'https://cssbuttons.app/',
        logo: 'https://data.textstudio.com/output/sample/animated/3/7/8/2/404-11-12873.gif',
        category: 'Design Resources',
        description: 'Buttons for the Web'
    },
    {
        id: 15, 
        name: 'uiverse',
        site: 'https://uiverse.io/',
        logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPdeW7lpEjiW0fLPH09HFrARpzH-2B8e9i0X_C8MK7CBK0vslPjVlqsKa_EPl_riwrCDw&usqp=CAU',
        category: 'Design Resources',
        description: 'Custom Elements made with CSS or Tailwind',
    },
    {
        id: 16,
        name: 'transition.css',
        site: 'https://www.transition.style/',
        logo: 'https://data.textstudio.com/output/sample/animated/3/7/8/2/404-11-12873.gif',
        category: 'Design Resources',
        description: 'Drop-in CSS transitions',
    },
    {
        id: 17,
        name: 'MagicPattern',
        site: 'https://www.magicpattern.design/tools/gradient-generator',
        logo: 'https://www.magicpattern.design/static/images/magicpattern-logo-2.png',
        category: 'Design Resources',
        description: 'Gradient Generator',
    },
    {
        id: 18,
        name: 'softr',
        site: 'https://www.softr.io/tools',
        logo: 'https://community.softr.io/uploads/db9110/original/1X/7a768145895be060d9cc6d934bae03d9dd408790.png',
        category: 'Design Resources',
        description: 'Create Designs, Edit and Generate Files',
    },
    {
        id: 19,
        name: '100L5',
        site: 'https://10015.io/',
        logo: 'https://10015.io/brand/logo-on-light.svg',
        category: 'Design Resources',
        description: 'Free All-in-One Toolbox',
    },
    {
        id: 20,
        name: 'getwaves',
        site: 'https://getwaves.io/',
        logo: 'https://www.bookmarks.design/media/image/getwaves.jpg',
        category: 'Design Resources',
        description: 'Make some waves!',
    },
    {
        id: 21,
        name: 'blobmaker',
        site: 'https://www.blobmaker.app/',
        logo: 'https://www.saashub.com/images/app/service_logos/31/54b3976986e1/large.png?1639105727',
        category: 'Design Resources',
        description: 'Free Generative Design Tool',
    },
    {
        id: 22,
        name: 'haikei',
        site: 'https://haikei.app/',
        logo: 'https://resourcesfordesigner.com/wp-content/uploads/2021/03/haikei-400x300.jpg',
        category: 'Design Resources',
        description: 'Web App to Generate Stunning Visual Content',
    },
    {
        id: 23,
        name: 'Clippy',
        site: 'https://bennettfeely.com/clippy/',
        logo: 'https://shots.codepen.io/username/pen/QWPKZR-800.jpg?version=1413313919',
        category: 'Design Resources',
        description: 'CSS Clip-Path Maker',
    },
    {
        id: 24, 
        name: 'SheCodes',
        site: 'https://generators.shecodes.io/',
        logo: 'https://www.shecodes.io/assets/branding/logo-shecodes-f9fa0540d113c086f61eb6e89466c0cbd24a42163b6a96d4b01da078803f53ee.png',
        category: 'Design Resources',
        description:'Generate Awesome CSS for your next project'
    }
]