export const cards = [
    {
        id: 1,
        name: 'Google Fonts',
        site: 'https://fonts.google.com/',
        logo: 'https://logos-world.net/wp-content/uploads/2021/03/Google-Fonts-Logo.png',
        category: 'Typography',
        description: 'A computer font and web services owned by Google',
    },
    {
        id: 2,
        name: 'Fonts in Use',
        site: 'https://fontsinuse.com/',
        logo: 'https://seeklogo.com/images/F/fonts-in-use-logo-6EA99A0816-seeklogo.com.png',
        category: 'Typography',
        description: 'An independent archive of typography',
    },
    {
        id: 3,
        name: 'Font Fabric',
        site: 'https://www.fontfabric.com/free-fonts/',
        logo: 'https://cdn.dribbble.com/users/58593/screenshots/1021155/media/79853350d5b66f10cfbeeea57094cf08.png?resize=400x300&vertical=center',
        category: 'Typography',
        description: 'Company for Font Type Design',
    },
    {
        id: 4, 
        name: 'Typo/Graphic',
        site: 'https://www.typographicposters.com/',
        logo: 'https://www.typographicposters.com/apple-touch-icon.png',
        category: 'Typography',
        description: 'Connect to Different Cultures Through Poster Design',
    },
    {
        id: 5,
        name: 'Color Hunt',
        site: 'https://colorhunt.co/',
        logo: 'https://colorhunt.co/img/color-hunt-logo-animation.gif',
        category: 'Color',
        description: 'Free and Open Platform For Color Inspiration',
    },
    {
        id: 6,
        name: 'Khroma',
        site: 'https://www.khroma.co/',
        logo: 'https://www.designupai.com/wp-content/uploads/2023/10/Khroma-Logo.png',
        category: 'Color',
        description: 'Uses AI to Learn which Colors You Like and Creates Palettes'
    },
    {
        id: 7, 
        name: 'Happy Hues',
        site: 'https://www.happyhues.co/',
        logo: 'https://uploads-ssl.webflow.com/6198a2e43048192ebafec2cc/63d13e7ca156bd4cf5d177b9_fDgNkoqEyjF1OI0HdDtD-S2EzhUKihaUVPAyJPjpL9k.png',
        category: 'Color',
        description: 'Curated Colors in Context',
    },
    {
        id: 8,
        name: 'Coolors',
        site: 'https://coolors.co/',
        logo: 'https://wpexpert.ca/wp-content/uploads/coolors-logo.jpg',
        category: 'Color',
        description: 'Fast Color Schemes Generator',    
    },
    {
        id: 9,
        name: 'Brand Colors',
        site: 'https://brandcolors.net/',
        logo: 'https://asset.brandfetch.io/id22o1wBNN/idlDger2sy.jpeg?updated=1706980420399',
        category: 'Color',
        description: 'Biggest Collection of Official Brand Color Codes'
    },
    {
        id: 10,
        name: 'DevDocs',
        site: 'https://devdocs.io/',
        logo: 'https://assets-global.website-files.com/61fc4082d1990015ce74e415/620fc3c7cba4a56fa0913796_Devdocs%20Logo%20Transpararent%20Dark.svg',
        category: 'Documentations',
        description: 'Combines multiple API documentations',
    },
    {
        id: 11,
        name: 'Figma',
        site: 'https://www.figma.com/',
        logo: 'https://cdn.sanity.io/images/599r6htc/localized/46a76c802176eb17b04e12108de7e7e0f3736dc6-1024x1024.png?w=804&h=804&q=75&fit=max&auto=format',
        category: 'Prototype',
        description: 'A collaborative web application for interface design',
    },
    {
        id: 12,
        name: 'Adobe XD',
        site: 'https://adobexdplatform.com/',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Adobe_XD_CC_icon.svg/1200px-Adobe_XD_CC_icon.svg.png',
        category: 'Prototype',
        description: 'A vector design tool for web and mobile applications',
    },
    {
        id: 13, 
        name: 'Typo/Graphic',
        site: 'https://www.typographicposters.com/',
        logo: 'https://www.typographicposters.com/apple-touch-icon.png',
        category: 'Typography',
        description: 'Connect to Different Cultures Through Poster Design',
    },
    {
        id: 14, 
        name: 'Typo/Graphic',
        site: 'https://www.typographicposters.com/',
        logo: 'https://www.typographicposters.com/apple-touch-icon.png',
        category: 'Typography',
        description: 'Connect to Different Cultures Through Poster Design',
    },
    {
        id: 15, 
        name: 'Typo/Graphic',
        site: 'https://www.typographicposters.com/',
        logo: 'https://www.typographicposters.com/apple-touch-icon.png',
        category: 'Typography',
        description: 'Connect to Different Cultures Through Poster Design',
    },
    {
        id: 16, 
        name: 'Typo/Graphic',
        site: 'https://www.typographicposters.com/',
        logo: 'https://www.typographicposters.com/apple-touch-icon.png',
        category: 'Typography',
        description: 'Connect to Different Cultures Through Poster Design',
    },
]