export const cards = [
    {
        id: 1,
        name: 'Google Fonts',
        site: 'https://fonts.google.com/',
        logo: 'https://logos-world.net/wp-content/uploads/2021/03/Google-Fonts-Logo.png',
        category: 'Typography',
        description: 'A computer font and web services owned by Google',
    },
    {
        id: 2,
        name: 'Fonts in Use',
        site: 'https://fontsinuse.com/',
        logo: 'https://seeklogo.com/images/F/fonts-in-use-logo-6EA99A0816-seeklogo.com.png',
        category: 'Typography',
        description: 'An independent archive of typography',
    },
    {
        id: 3,
        name: 'Font Fabric',
        site: 'https://www.fontfabric.com/free-fonts/',
        logo: 'https://cdn.dribbble.com/users/58593/screenshots/1021155/media/79853350d5b66f10cfbeeea57094cf08.png?resize=400x300&vertical=center',
        category: 'Typography',
        description: 'Company for Font Type Design',
    },
    {
        id: 4,
        name: 'aaa',
        site: 'https://www.fontfabric.com/free-fonts/',
        logo: 'https://cdn.dribbble.com/users/58593/screenshots/1021155/media/79853350d5b66f10cfbeeea57094cf08.png?resize=400x300&vertical=center',
        category: 'Typography',
        description: 'Company for Font Type Design',
    },
    {
        id: 5,
        name: 'bbbbbb',
        site: 'https://www.fontfabric.com/free-fonts/',
        logo: 'https://cdn.dribbble.com/users/58593/screenshots/1021155/media/79853350d5b66f10cfbeeea57094cf08.png?resize=400x300&vertical=center',
        category: 'Typography',
        description: 'Company for Font Type Color',
    },
    {
        id: 6,
        name: 'cccc',
        site: 'https://www.fontfabric.com/free-fonts/',
        logo: 'https://cdn.dribbble.com/users/58593/screenshots/1021155/media/79853350d5b66f10cfbeeea57094cf08.png?resize=400x300&vertical=center',
        category: 'Typography',
        description: 'Company for Font Type Color',
    },
    {
        id: 7,
        name: 'ddd',
        site: 'https://www.fontfabric.com/free-fonts/',
        logo: 'https://cdn.dribbble.com/users/58593/screenshots/1021155/media/79853350d5b66f10cfbeeea57094cf08.png?resize=400x300&vertical=center',
        category: 'Typography',
        description: 'Company for Font Type Color',
    },
    {
        id: 8,
        name: 'eee',
        site: 'https://www.fontfabric.com/free-fonts/',
        logo: 'https://cdn.dribbble.com/users/58593/screenshots/1021155/media/79853350d5b66f10cfbeeea57094cf08.png?resize=400x300&vertical=center',
        category: 'Typography',
        description: 'Company for Font Type Color',
    },
    {
        id: 10,
        name: 'fff',
        site: 'https://www.fontfabric.com/free-fonts/',
        logo: 'https://cdn.dribbble.com/users/58593/screenshots/1021155/media/79853350d5b66f10cfbeeea57094cf08.png?resize=400x300&vertical=center',
        category: 'Typography',
        description: 'Company for Font Type Color',
    },
]